/** @type {import(&apos;prettier&apos;).Config} */
module.exports = {
  bracketSpacing: true,
  endOfLine: &quot;lf&quot;,
  semi: true,
  singleQuote: false,
  tabWidth: 2,
  trailingComma: &quot;all&quot;,
  printWidth: 80,
  importOrder: [
    &quot;^(react/(.*)$)|^(react$)&quot;,
    &quot;^(next/(.*)$)|^(next$)&quot;,
    &quot;<THIRD_PARTY_MODULES>&quot;,
    &quot;&quot;,
    &quot;^types$&quot;,
    &quot;^@/env(.*)$&quot;,
    &quot;^@/types/(.*)$&quot;,
    &quot;^@/config/(.*)$&quot;,
    &quot;^@/lib/(.*)$&quot;,
    &quot;^@/hooks/(.*)$&quot;,
    &quot;^@/components/ui/(.*)$&quot;,
    &quot;^@/components/(.*)$&quot;,
    &quot;^@/styles/(.*)$&quot;,
    &quot;^@/app/(.*)$&quot;,
    &quot;&quot;,
    &quot;^[./]&quot;,
  ],
  importOrderSeparation: false,
  importOrderSortSpecifiers: true,
  importOrderBuiltinModulesToTop: true,
  importOrderParserPlugins: [&quot;typescript&quot;, &quot;jsx&quot;, &quot;decorators-legacy&quot;],
  importOrderMergeDuplicateImports: true,
  importOrderCombineTypeAndValueImports: true,
  plugins: [&quot;@ianvs/prettier-plugin-sort-imports&quot;, &quot;prettier-plugin-tailwindcss&quot;],
};